### ISSUE TITLE
failed to recognize APR_INT64_T_FMT on this platform

### ISSUE THREAD

**Issue by pauledd** [OpenVuPlus/openvuplus_3.0#1]
Hi

I just tried to build openvuplus on a gentoo system.

What I did so far:
```
git clone git://code.vuplus.com/git/openvuplus_3.0.git
cd openvuplus_3.0
make image MACHINE=vuuno4k
```

It run fine until it tried to configure subversion-1.8.13. 
I get this error:
```
checking for apr_int64_t Python/C API format string...
| configure: error: failed to recognize APR_INT64_T_FMT on this platform
```
the log.do_configure is here:
https://pastebin.com/QkU3SPGz
the config.log is here:
https://pastebin.com/TjUyFyg8

any ideas anyone whats the reason for the error?

**Comment by pauledd** [comment]
Solved by adding
`BUILD_CPPFLAGS += "-P"`
to  openvuplus_3.0/openembedded-core/meta/recipes-devtools/subversion/subversion_1.8.13.bb

**Comment by AxelNennker** [comment]
Why is this issue closed when it is not fixed in the latest openvuplus_3.0 ?
 I just created a fresh Ubuntu 16.04, installed the required packages and cloned git://code.vuplus.com/git/openvuplus_3.0.git
The image build stopped with exactly this issue.
I added the BUILD_CPPFLAGS line as suggested by @pauledd and now building the subversion receipt works.

So this issue is fixed in the latest master of openembedded-core but not in the version used by openvuplus_3.0
https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-devtools/subversion/subversion_1.9.6.bb
